[package]
name = "aster"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
comemo = "0.5"
data-url = "0.3"
include_dir = "0.7"
lightningcss = "=1.0.0-alpha.72"
pathdiff = "0.2"
seahash = "4.1.0"
syntect = { version = "5.3", features = ["default-syntaxes", "default-themes", "dump-load"] }
termcolor = "1"
thiserror = "2"
toml = "1.1"
typst = "0.15.1"
typst-eval = "0.15.1"
typst-html = "0.15.1"
typst-kit = { version = "0.15.1", features = ["emit-diagnostics", "scan-fonts", "system-downloader", "system-files", "watcher"] }
typst-library = "0.15.1"
typst-svg = "0.15.1"
walkdir = "2.5"

[dev-dependencies]
comemo = { version = "0.5", features = ["testing"] }
tempfile = "3"
