[package]
name = "aster"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
syntect = { version = "5.3", features = ["default-themes", "dump-load"] }
toml = "1.1"
typst = "0.15.1"
typst-html = "0.15.1"
typst-kit = { version = "0.15.1", features = ["system-files", "system-downloader", "scan-fonts", "emit-diagnostics"] }
termcolor = "1"
