[project]
name = "aster-starlog"

[site]
title = "Starlog"
description = "The latest updates from Nebulous."
language = "en"

[highlight]
themes = { light = "InspiredGitHub", dark = "base16-eighties.dark" }
