[project]
name = "aster-starlight"

[site]
title = "Aster Docs"
description = "A documentation site built with Aster and Typst."
language = "en"
repository = "https://github.com/Wybxc/aster"

[docs]
edit-base = "https://github.com/Wybxc/aster/edit/main/examples/starlight/content/docs/"

[highlight]
themes = { light = "InspiredGitHub", dark = "base16-eighties.dark" }
